
DEMO_BABY_ID = "002"
BABY_PROFILE_DDB_TABLE = 'SparcBusyBabyProfile'
DAILY_RECORD_DDB_TABLE = 'SparcBusyBabyDailyRecord'

CREATE_BABY_INTENT = "createBaby"
CREATE_BATH_INTENT = "createBathRecord"
CREATE_DIAPER_INTENT = "createDiaperRecord"
CREATE_MILK_INTENT = "createFeedMilk"
CREATE_FEVER_INTENT = "createFeverRecord"
CREATE_FOOD_INTENT = "createFoodRecord"
CREATE_FORMULA_INTENT = "createFormulaMilk"
CREATE_NURSING_INTENT = "createNursingMilk"
CREATE_GROWTH_INTENT = "createGrowthRecord"
CREATE_MEDICATION_INTENT = "createMedicationRecord"
CREATE_SICK_INTENT = "createSickRecord"
CREATE_SLEEP_INTENT = "createSleepRecord"
CREATE_VACCINE_INTENT = "createVaccineRecord"

# CREATE_BABY_INTENT = "createBaby"
GENDER = "baby_gender"
FIRST_NAME = "first_name"
LAST_NAME = "last_name"
SHE_HE = "pronounS"
BIRTHDAY = "birthday"
DELIVERY_TIME = "delivery_time"

# CREATE_BATH_INTENT = "createBathRecord"
# FIRST_NAME = "first_name"
BATH_TIME = "bath_time"
BATH_DATE = "bath_date"
BATH_NOTE = "bath_note"

# CREATE_DIAPER_INTENT = "createDiaperRecord"
# FIRST_NAME = "first_name"
DIAPER_TYPE = "diaper_type"
DIAPER_TIME = "diaper_time"
DIAPER_DATE = "diaper_date"
DIAPER_NOTE = "diaper_note"

# CREATE_FEVER_INTENT = "createFeverRecord"
# FIRST_NAME = "first_name"
TEMPERATURE = "temperature"
TEMPERATURE_TYPE = "temperature_type"
TEMPERATURE_TIME = "temperature_time"
TEMPERATURE_DATE = "temperature_date"

# CREATE_FOOD_INTENT = "createFoodRecord"
# FIRST_NAME = "first_name"
FOOD_TYPE = "food_type"
FOOD_TIME = "food_time"
FOOD_DATE = "food_date"
FOOD_NOTE = "food_note"

# CREATE_FORMULA_INTENT = "createFormulaMilk"
# FIRST_NAME = "first_name"
FORMULA_VOLUME = "formula_volume"
FORMULA_TIME = "formula_time"
FORMULA_DATE = "formula_date"
FORMULA_NOTE = "formula_note"

# CREATE_NURSING_INTENT = "createNursingMilk"
# FIRST_NAME = "first_name"
START_END = "start_end"
NURSING_TIME = "nursing_milk_time"
NURSING_DATE = "nursing_milk_date"
NURSING_NOTE = "nursing_milk_note"

# CREATE_GROWTH_INTENT = "createGrowthRecord"
# FIRST_NAME = "first_name"
GROWTH_TYPE = "growth_info"
GROWTH_DATE = "growth_info_date"
GROWTH_DATA = "growth_data"

# CREATE_MEDICATION_INTENT = "createMedicationRecord"
# FIRST_NAME = "first_name"
MED_TYPE = "medication_type"
MED_TIME = "medication_time"
MED_DATE = "medication_date"
MED_NOTE = "medication_note"

# CREATE_SICK_INTENT = "createSickRecord"
# FIRST_NAME = "first_name"
SICK_SYMPTOM = "symptom"
SICK_TIME = "sick_time"
SICK_DATE = "sick_date"
SICK_NOTE = "sick_note"

# CREATE_SLEEP_INTENT = "createSleepRecord"
# FIRST_NAME = "first_name"
# START_END = "start_end"
SLEEP_TIME = "sleep_time"
SLEEP_DATE = "sleep_date"
SLEEP_NOTE = "sleep_note"

# CREATE_VACCINE_INTENT = "createVaccineRecord"
# FIRST_NAME = "first_name"
VACCINE_TYPE = "vaccine_type"
VACCINE_DATE = "vaccine_date"
VACCINE_NOTE = "vaccine_note"