
DEMO_BABY_ID = "003"
BABY_PROFILE_DDB_TABLE = 'SparcBusyBabyProfile'
DAILY_RECORD_DDB_TABLE = 'SparcBusyBabyDailyRecord'

ADD_BABY = "createBaby"
ADD_BATH = "createBathRecord"
ADD_DIAPER = "createDiaperRecord"
ADD_MILK = "createFeedMilk"
ADD_FEVER = "createFeverRecord"
ADD_FOOD = "createFoodRecord"
ADD_FORMULA = "createFormulaMilk"
ADD_NURSING = "createNursingMilk"
ADD_GROWTH = "createGrowthRecord"
ADD_MEDICATION = "createMedicationRecord"
ADD_SICK = "createSickRecord"
ADD_SLEEP = "createSleepRecord"
ADD_VACCINE = "createVaccineRecord"
GET_RECORD = "getRecord"

# ADD_BABY = "createBaby"
GENDER = "baby_gender"
FIRST_NAME = "first_name"
LAST_NAME = "last_name"
SHE_HE = "pronounS"
BIRTHDAY = "birthday"
DELIVERY_TIME = "delivery_time"

# ADD_BATH = "createBathRecord"
# FIRST_NAME = "first_name"
BATH_TIME = "bath_time"
BATH_DATE = "bath_date"
BATH_NOTE = "bath_note"

# ADD_DIAPER = "createDiaperRecord"
# FIRST_NAME = "first_name"
DIAPER_TYPE = "diaper_type"
DIAPER_TIME = "diaper_time"
DIAPER_DATE = "diaper_date"
DIAPER_NOTE = "diaper_note"

# ADD_FEVER = "createFeverRecord"
# FIRST_NAME = "first_name"
TEMPERATURE_DATA = "temperature"
TEMPERATURE_TYPE = "temperature_type"
TEMPERATURE_TIME = "temperature_time"
TEMPERATURE_DATE = "temperature_date"

# ADD_FOOD = "createFoodRecord"
# FIRST_NAME = "first_name"
FOOD_TYPE = "food_type"
FOOD_TIME = "food_time"
FOOD_DATE = "food_date"
FOOD_NOTE = "food_note"

# ADD_FORMULA = "createFormulaMilk"
# FIRST_NAME = "first_name"
FORMULA_VOLUME = "formula_volume"
FORMULA_TIME = "formula_time"
FORMULA_DATE = "formula_date"
FORMULA_NOTE = "formula_note"

# ADD_NURSING = "createNursingMilk"
# FIRST_NAME = "first_name"
START_END = "start_end"
NURSING_TIME = "nursing_milk_time"
NURSING_DATE = "nursing_milk_date"
NURSING_NOTE = "nursing_milk_note"

# ADD_GROWTH = "createGrowthRecord"
# FIRST_NAME = "first_name"
GROWTH_TYPE = "growth_info"
GROWTH_DATE = "growth_info_date"
GROWTH_DATA = "growth_data"

# ADD_MEDICATION = "createMedicationRecord"
# FIRST_NAME = "first_name"
MED_TYPE = "medication_type"
MED_TIME = "medication_time"
MED_DATE = "medication_date"
MED_NOTE = "medication_note"

# ADD_SICK = "createSickRecord"
# FIRST_NAME = "first_name"
SICK_SYMPTOM = "symptom"
SICK_TIME = "sick_time"
SICK_DATE = "sick_date"
SICK_NOTE = "sick_note"

# ADD_SLEEP = "createSleepRecord"
# FIRST_NAME = "first_name"
# START_END = "start_end"
SLEEP_TIME = "sleep_time"
SLEEP_DATE = "sleep_date"
SLEEP_NOTE = "sleep_note"

# ADD_VACCINE = "createVaccineRecord"
# FIRST_NAME = "first_name"
VACCINE_TYPE = "vaccine_type"
VACCINE_DATE = "vaccine_date"
VACCINE_NOTE = "vaccine_note"

# GET_RECORD = "getRecord"
RECORD_TYPE = "get_record_type"
RECORD_DATE = "record_date"